---
  - name: install nginx
    package:
      name: nginx

  - name: ensure enabled/started
    service:
      name: nginx
      state: started
      enabled: true

  - name: install custom html
    copy:
      src: index.html
      dest: /usr/share/nginx/html/index.html
      backup: yes
